### PR TITLE
Support to use specific container for Pontoon

### LINKED ISSUE #71: Session is container dependant
### Steps to reproduce

1. Log in to Pontoon in a "Personal" container
2. Switch to "Work" container
3. Switch bask to "Personal" container
4. Somewhere along the way you should start seeing an exclamtion mark (warning/error)

### Expected behavior
I should be able to switch tabs and containers freely while keeping Pontoon Tools running and logged in.

### Actual behavior
Unexpected errors due to tab/container switching.

### PR DESCRIPTION
**Pull request by MikkCZ**
fix #71 

TODO:
- [x] Allow to select container in options UI.
- [x] Any requests to Pontoon, that need cookies, use those from the selected container. Only the session cookie may actually be needed, and the rest omitted.
- [x] Update data on the fly only from tabs in the selected container. Use [tabs.onUpdated](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/onUpdated) and [tabs.executeScript](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript) to load the content script only to tabs in the expected container.
- [x] When a container selection changes, (un)load content scripts in any open tab with Pontoon.
    - Data live update script does not make any sense to load into potentially outdated tabs.
    - The bell icon sync script makes sense to enable in open tabs for changes from background.
- [x] When a container selection changes, reload data from Pontoon.
- [x] Secure request from RemotePontoon with safe tokens (valid for single requests only?).
- [x] Update registered listeners in `DataRefresher` and `DataFetcher` when `RemotePontoon.getBaseUrl` changes.
- [x] Document `DataFetcher` and the rest of new code.
- [ ] ~Make the related permissions optional, so we do not force enabled container tabs.~ [bug 1475834](https://bugzilla.mozilla.org/show_bug.cgi?id=1475834)
- [x] Externalize defaults from `Options.js` to a JSON file (may differ between FF and Chrome?).
- [x] Hide all options in Chrome and test for regressions.

### CODE REVIEW

**Comment by MikkCZ** [comment]
I hope to finish this probably next weekend. @yarons may I ask you then to test a pre-release version of this feature, when it's available?

**Comment by yarons** [comment]
It would be a great honor, I'd love to.

**Comment by MikkCZ** [comment]
@yarons Here is a test package of Pontoon Tools with the requested feature. To test it, decompress the archive and follow the steps from [Temporary installation in Firefox](https://developer.mozilla.org/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) document. After you load the add-on, you can set the container you use for Pontoon in the add-on settings.

It's still WIP, but it should mostly work as expected feature-wise. Please **reboot Firefox after you are done with the testing** to ensure the test build is removed, or even better test it in a standalone [profile](https://support.mozilla.org/kb/profiles-where-firefox-stores-user-data), which you can delete afterwards. There is a severe _security risk if you use it longer than few minutes_ that your session cookie may be exposed to some XSS attack.
[pontoon_tools-3.3.0a1.zip](https://github.com/MikkCZ/pontoon-tools/files/2195652/pontoon_tools-3.3.0a1.zip)

**Comment by yarons** [comment]
OK, sorry for the late response, thank you for the fix.

If I understand correctly it's now bound to the "General" container, so if I want to work on Pontoon in a dedicated container I should still log in from the "General" one and not "Personal" or a custom created "Localization" container.

Am I right?

**Comment by MikkCZ** [comment]
I am happy you found the setting, @yarons . Here is a test version that should be safe to use. Can you please test and verify it works for you too? If so, I will release it to public probably the next week.

[pontoon_tools-3.3.0a2.zip](https://github.com/MikkCZ/pontoon-tools/files/2198940/pontoon_tools-3.3.0a2.zip)

**Comment by MikkCZ** [comment]
I should be back this week to finish this. Mainly I need to verify the are no effects in  Chrome, do some bugfixes from the other tickets and release. ;)

**Comment by yarons** [comment]
Cool, I'm a little busy at work but I'll try to talk to some friends to help verify the Add on, thank you!

**Pull request merged**
